ThorlabsLTS:
  alias: positioner_system_default
  x:  
    serial: 45286264
    model: LTS150
    min_position: 0           # [mm]
    max_position: 150         # [mm]
    max_velocity: 20          # [mm s^-1]
    max_acceleration: 20      # [mm s^-2]
    position_accuracy: 0.01   # [mm]
  y:
    serial: 45289034
    model: LTS150
    min_position: 0           # [mm]
    max_position: 150         # [mm]
    max_velocity: 20          # [mm s^-1]
    max_acceleration: 20      # [mm s^-2]
    position_accuracy: 0.01   # [mm]
  z:
    serial: 45293664
    model: LTS150
    min_position: 0           # [mm]
    max_position: 150         # [mm]
    max_velocity: 20          # [mm s^-1]
    max_acceleration: 20      # [mm s^-2]
    position_accuracy: 0.01   # [mm]
